config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.views.generic.base import RedirectView
from political_sisterhood.pages.views import PageDetailView
from political_sisterhood.issue.views import IssueAutocomplete
from political_sisterhood.search.views import MySearchView
from .views import HomePage, Mailchimp, ContactUs

urlpatterns = [
    url(r'^$', HomePage.as_view(), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^news/$', TemplateView.as_view(template_name='pages/news.html'), name='news'),
    url(r'^contact-us/$', ContactUs.as_view(), name='contact'),
    url(r'^coming-soon/$', TemplateView.as_view(template_name='pages/soon.html'), name='coming-soon'),
    url(r'^issue-ac/', IssueAutocomplete.as_view(), name="issue-autocomplete"),
    # UTILITY VIEWS
    url(r'mailchimp-signup/$', Mailchimp, name='mailchimp'),
    url(r'^report_builder/', include('report_builder.urls')),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^profile/', include('political_sisterhood.users.urls', namespace='users')),
    url(r'^accounts/social/connections/$', RedirectView.as_view(pattern_name='users:redirect', permanent=True)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^candidates/', include('political_sisterhood.candidate.urls', namespace='candidate')),
    url(r'^races/', include('political_sisterhood.races.urls', namespace='races')),
    url(r'^jobs/', include('political_sisterhood.jobs.urls', namespace='jobs')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^admin/dynamic_raw_id/', include('dynamic_raw_id.urls')),
    url(r'^search/?$', MySearchView.as_view(), name='search'),

    # Your stuff: custom urls includes go here
    url(r'^(?P<slug>[\w.@+-]+)/$', PageDetailView.as_view()),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

political_sisterhood/candidate/urls.py
from django.conf.urls import include, url
from .views import CandidateView, StateListView, AllCandidates,\
                   UpdateCandidateInvite, CandidatePricing,\
                   CandidateIssueReport, CandidatePaywall,\
                   CreateCandidate
from django.views.generic import TemplateView
app_name = 'candidate'

urlpatterns = [
    url(r'^$',
        AllCandidates.as_view(),
        name='all'
        ),
    url(r'^pricing/$',
        TemplateView.as_view(template_name='pages/soon.html'),
        name='pricing'),
    url(r'^limit/$',
        CandidatePaywall.as_view(),
        name='paywall'
        ),
    url(r'^issue/$',
        CandidateIssueReport,
        name='issue'
        ),
    url(r'^update/(?P<hash>[\w.@+-]+)/$',
        UpdateCandidateInvite.as_view(),
        name='update'
        ),
    url(r'^create/$',
        CreateCandidate.as_view(),
        name='create'
        ),
    url(r'(?P<state>[\w.@+-]+)/(?P<slug>[\w.@+-]+)/$',
        CandidateView.as_view(),
        name='detail'
        ),
    url(r'(?P<state>[\w.@+-]+)/$',
        StateListView.as_view(),
        name='state'
        ),
]

political_sisterhood/jobs/urls.py
from django.conf.urls import include, url
from .views import JobsAll, JobsPost

app_name = 'jobs'

urlpatterns = [
    url(r'^$',
        JobsAll.as_view(),
        name='all'
    ),
    url(r'post/$',
        JobsPost.as_view(),
        name='post'
    ),
]

political_sisterhood/races/urls.py
from django.conf.urls import url
from .views import RaceAdd

app_name = 'races'

urlpatterns = [
    url(r'^add/$',
        RaceAdd.as_view(),
        name='all'
    ),

]

political_sisterhood/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^settings/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

political_sisterhood/search/models.py
# empty

political_sisterhood/candidate/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.views.generic import DetailView, CreateView,\
                                 TemplateView, UpdateView,\
                                 ListView, RedirectView
from django.core.mail import send_mail
from templated_email import send_templated_mail
from django.contrib import messages
from .models import Candidate, CandidateInvite, College, CandidateUpdate
from political_sisterhood.issue.models import CandidateIssue
from haystack.generic_views import SearchView as BaseFacetedSearchView
from political_sisterhood.races.models import State, Race
import logging
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .forms import CandidateForm
from political_sisterhood.search.forms import SearchForm
from haystack.query import SearchQuerySet, EmptySearchQuerySet, SQ
from haystack.inputs import AutoQuery
import urllib.parse as urlparse
logger = logging.getLogger(__name__)
# Create your views here.


def sendingEmail(candidate, new_data):
    candidate = Candidate.objects.get(id=candidate)
    from django.core import serializers
    try:
        send_templated_mail(
            template_name='updated',
            from_email="Political Sisterhood <info@politicalsisterhood.org>",
            recipient_list=['chris@politicalsisterhood.com',
                            'susan@politicalsisterhood.com'],
            context={
                'name': candidate.full_name,
                'url': candidate.get_absolute_url(),
                'candidate': candidate,
                'instance': new_data
            }
        )
    except Exception as e:
        logger.error(e)


class AllCandidates(BaseFacetedSearchView):
    template_name = "candidate/all.html"
    facet_fields= ['party']
    form_class = SearchForm
    paginate_by = 12
    paginate_orphans = 2

    # All CHANGES NEED TO BE DONE IN SEARCH/VIEWS AND CANDIDATE/VIEWS
    def get_queryset(self):
        queryset = SearchQuerySet().filter(active=True).order_by('first_name')
        # further filter queryset based on some set of criteria
        party = self.request.GET.getlist('party', '')
        party_or = ""
        college = self.request.GET.getlist('college', '')
        college_or = ""
        state = self.request.GET.getlist('state', '')
        state_or = ""
        issues = self.request.GET.getlist('issues', '')
        issues_or = ""
        race = self.request.GET.getlist('race', '')
        race_or = ""
        race_type = self.request.GET.getlist('race_type', '')
        race_type_or = ""
        women = self.request.GET.get('women', '')
        q = self.request.GET.get('q', '')
        page = self.request.GET.get('page', '')
        search = ''.join(party) + q + page
        if search == "":
            search = "null"
        if party:
            for facet in party:
                party_or += 'party: "%s"' % (facet)
            queryset = queryset.narrow(party_or)
        if college:
            for facet in college:
                college_or += 'college: "%s"' % (facet)
            queryset = queryset.narrow(college_or)
        if state:
            for facet in state:
                state_or += 'state: "%s"' % (facet)
            queryset = queryset.narrow(state_or)
        if issues:
            for facet in issues:
                issues_or += 'issues: "%s"' % (facet)
            queryset = queryset.narrow(issues_or)
        if race:
            for facet in race:
                race_or += 'race: "%s"' % (facet)
            queryset = queryset.narrow(race_or)
        if race_type:
            for facet in race_type:
                race_type_or += 'race_type: "%s"' % (facet)
            queryset = queryset.narrow(race_type_or)
        if q:
            queryset = queryset.filter(SQ(text=AutoQuery(q))|SQ(title=AutoQuery(q)))
        if women:
            queryset = queryset.filter(women=True)
        return queryset

    def form_valid(self, form):
        context = self.get_context_data(**{
            self.form_name: form,
            'object_list': self.get_queryset()
        })
        return self.render_to_response(context)

    def form_invalid(self, form):
        context = self.get_context_data(**{
            self.form_name: form,
            'object_list': self.get_queryset()
        })
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q','')
        context['party'] = self.request.GET.getlist('party', '')
        context['college'] = self.request.GET.getlist('college', '')
        context['state'] = self.request.GET.getlist('state', '')
        context['issues'] = self.request.GET.getlist('issues', '')
        women = self.request.GET.get('women', '')
        if women == True or women == 'on':
            context['women'] = True
        context['race_type'] = self.request.GET.getlist('race_type', '')
        return context


class CandidateView(DetailView):
    model = Candidate
    template_name = "candidate/detail.html"

    def dispatch(self, *args, **kwargs):
        user = self.request.user.is_authenticated
        if 'visited' in self.request.session:
            visits = self.request.session['visited']
        else:
            visits = None
        if not user:
            if visits and len(visits) > 3:
                return redirect(reverse('candidate:paywall'))
            visited = []
            candidate = self.get_object().id
            if visits:
                visited.extend(visits)
                if not candidate in visits:
                    visited.append(candidate)
            else:
                visited.append(candidate)
            self.request.session['visited'] = visited
        return super().dispatch(*args, **kwargs)

    def get_object(self):
        slug = self.kwargs['slug']
        candidate = Candidate.objects.get(slug=slug)
        return candidate

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['approved'] = False
        if self.request.GET.get('approved') == 'pending':
            context['approved'] = True
        elif self.get_object().approved:
            context['approved'] = True
        return context


class StateListView(ListView):
    model = Candidate
    template_name = "state/list.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        state =State.objects.get(state=self.kwargs['state'].upper())
        data['object'] = state
        return data

    def get_queryset(self):
        state = Candidate.objects.filter(state=self.kwargs['state'])
        return state


class UpdateCandidateInvite(UpdateView):
    # specify a custom ModelForm
    form_class = CandidateForm
    template_name = "candidate/update.html"

    def get_object(self, queryset=None):
        # get the existing object or created a new one
        candidate = get_object_or_404(CandidateInvite, md5_email=self.kwargs['hash'])
        if candidate.candidate:
            obj = Candidate.objects.get(id=candidate.candidate.id)
            CandidateInvite.objects.filter(md5_email=self.kwargs['hash']).update(candidate=obj)
        else:
            obj = None
        return obj

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['contact'] = CandidateInvite.objects.get(md5_email=self.kwargs['hash'])
        return data

    def form_valid(self, form):
        instance = form.save(commit=False)
        try:
            sendingEmail(instance.id, instance)
        except Exception as e:
            logger.error(e)
        instance.save()
        try:
            CandidateInvite.objects.filter(md5_email=self.kwargs['hash']).update(used=True)
            issue1, create = CandidateIssue.objects.get_or_create(candidate=instance,
                                                                  issue=form.cleaned_data.get('issue1'),
                                                                  desc=form.cleaned_data.get('issue1_detail'))
            issue2, created = CandidateIssue.objects.get_or_create(candidate=instance,
                                                                   issue=form.cleaned_data.get('issue2'),
                                                                   desc=form.cleaned_data.get('issue2_detail'))
            issue3, created = CandidateIssue.objects.get_or_create(candidate=instance,
                                                                   issue=form.cleaned_data.get('issue3'),
                                                                   desc=form.cleaned_data.get('issue3_detail'))
            college, create = College.objects.get_or_create(name=form.cleaned_data['college_free'])
            Candidate.objects.filter(id=instance.id).update(issue1=issue1.issue_num,
                                                            issue2=issue2.issue_num,
                                                            issue3=issue3.issue_num,
                                                            race_name=form.cleaned_data.get('race_name'),
                                                            college=college, approval="Pending")
            try:
                CandidateUpdate.objects.create(email=form.cleaned_data.get('update_email'),
                                               first_name=form.cleaned_data.get('update_first_name'),
                                               last_name=form.cleaned_data.get('update_last_name'),
                                               note=form.cleaned_data.get('update_note', ''),
                                               candidate=instance)
            except Exception as e:
                logger.error(e)
        except Exception as e:

political_sisterhood/issue/views.py
from dal import autocomplete
from django.utils.translation import ugettext as _
from django import http
from .models import Issue
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator


import logging

logger = logging.getLogger(__name__)

@method_decorator(csrf_exempt, name='dispatch')
class IssueAutocomplete(autocomplete.Select2QuerySetView):
    create_field = "name"

    def post(self, request):
        text = request.POST.get('text', None)

        if text is None:
            return http.HttpResponseBadRequest()

        parent = Issue.objects.get(name="Other")
        try:
            result, create = Issue.objects.get_or_create(name=text, parent=parent)
        except Exception as e:
            logger.error(e)

        return http.JsonResponse({
            'id': result.pk,
            'text': self.get_result_label(result),
        })

    def get_queryset(self):
        qs = Issue.objects.filter(parent__isnull=True)
        if self.q:
            qs = qs.filter(name__istartswith=self.q)
        return qs

    def get_create_option(self, context, q):
        """Form the correct create_option to append to results."""
        create_option = []
        display_create_option = False
        if self.create_field and q:
            display_create_option = True
            # Don't offer to create a new option if a
            # case-insensitive) identical one already exists
            existing_options = (self.get_result_label(result).lower()
                                for result in context['object_list'])
            if q.lower() in existing_options:
                display_create_option = False
        if display_create_option:
            create_option = [{
                'id': q,
                'text': _('Create "%(new_value)s"') % {'new_value': q},
                'create_id': True,
            }]
        return create_option

political_sisterhood/jobs/views.py
from django.shortcuts import render
from django.views.generic import DetailView, CreateView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class JobsAll(TemplateView):
    template_name = "jobs/all.html"

class JobsPost(LoginRequiredMixin, TemplateView):
    template_name = "jobs/post.html"

political_sisterhood/pages/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from .models import Page
# Create your views here.

class PageDetailView(DetailView):
    model = Page
    template_name = 'pages/detail.html'
    slug_url_kwarg = 'slug'

political_sisterhood/templates/pages/contact.html
{% extends 'base.html' %} {% block content %}
<section id="content" style="margin-bottom: 0px;">
  <div class="content-wrap">
    <div class="container clearfix">
      <div class="postcontent nobottommargin">
        <h3>Contact Us</h3>
        <div class="contact-widget">
          <form class="nobottommargin" id="contact" name="contact" action="" method="post" novalidate="novalidate">
            {% csrf_token %}
            <div class="form-process"></div>
            <div class="col_one_third">
              <label for="template-contactform-name">Name <small>*</small></label>
              <input type="text" id="name" name="name" value="" class="sm-form-control required">
            </div>
            <div class="col_one_third">
              <label for="template-contactform-email">Email <small>*</small></label>
              <input type="email" id="email" name="email" value="" class="required email sm-form-control">
            </div>
            <div class="col_one_third col_last">
              <label for="template-contactform-phone">Phone</label>
              <input type="text" id="phone" name="phone" value="" class="sm-form-control">
            </div>

            <div class="clear"></div>
            <div class="col_full">
              <label for="template-contactform-subject">Issue <small>*</small></label>
                <select class="form-control required" name="issue" required>
                <option disabled selected value>-- Please Specify --</option>
                <option>Request a Demo</option>
                <option>Issue with Candidate</option>
                <option>Sales Inquiry</option>
                <option>Customer Support</option>
                <option>Other</option>
                </select>
            </div>
            <div class="clear"></div>
            <div class="col_full">
              <label for="template-contactform-message">Message <small>*</small></label>
              <textarea class="required sm-form-control" id="message" name="message" rows="6" cols="30"></textarea>
            </div>
            <div class="col_full hidden">
              <input type="text" id="botcheck" name="botcheck" value="" class="sm-form-control">
            </div>
            <div class="col_full">
              <button class="button button-3d nomargin" type="submit" id="submit" name="submit" value="submit">Send Message</button>
            </div>
          </form>
        </div>
      </div>
      <div class="sidebar col_last nobottommargin">
        <abbr title="Email Address"><strong>Email:</strong></abbr> info@politicalsisterhood.com
        <div class="widget noborder notoppadding">
            <a href="https://www.facebook.com/politicalsisterhood/" class="social-icon si-small si-dark si-facebook">
                <i class="icon-facebook"></i>
                <i class="icon-facebook"></i>
            </a>
            <a href="https://twitter.com/@politicalsister" class="social-icon si-small si-dark si-twitter">
                <i class="icon-twitter"></i>
                <i class="icon-twitter"></i>
            </a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

political_sisterhood/templates/pages/detail.html
{% extends "base.html" %}
{% load static %} {% block seo_title %} {{object.title}} - Political Sisterhood {% endblock %} {% block content %}
<section id="page-title" class="page-title-mini page-title-nobg">
  <div class="container clearfix">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{object.title}}</li>
    </ol>
  </div>
</section>
<section class="themebg"></section>
<section id="content">
  <div class="container clear-bottommargin clearfix toppadding-sm bottompadding-sm">
      <h3>{{object.title}}</h3>
      {{object.content|safe}}
  </div>
</section>
{% endblock %}

political_sisterhood/templates/pages/general.html
{% extends "base.html" %}
{% load static %} {% block seo_title %}{{object.title}} - Political Sisterhood {% endblock %} {% block content %}
<section id="page-title" class="page-title-mini page-title-nobg">
  <div class="container clearfix">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{object.title}}</li>
    </ol>
  </div>
</section>
<section class="themebg"></section>
<section id="content">
  <div class="container clear-bottommargin clearfix toppadding-sm bottompadding-sm">
    <div class="heading-block">
      {{object.content}}
    </div>
  </div>
</section>
{% endblock %}

political_sisterhood/templates/pages/home.html
{% extends "base.html" %} {% load static %}
{% block fullwidth %}
<div class="clearfix row align-items-center">
<div class="col-lg-5 col-md-5 col-12 col-sm-12 col-xs-12 leftpadding-lg nomargin d-sm-padding">
        <div class="heading-block">
            <h1>Time to <strong>Represent</strong></h1>
            <span>Because 20% is not enough™</span>
        </div>
        <a href="#" class="button button-3d button-large">Join Us</a>
</div>
<div class="col-lg-7 col-md-7 col-xs-12 nomargin d-none d-sm-none d-md-block">
    <div id="portfolio" class="portfolio grid-container portfolio-3 portfolio-full portfolio-nomargin portfolio-notitle clearfix">
    {% for can in candidate %}
      <article class="portfolio-item pf-media pf-icons">
        <div class="portfolio-image">
            <a href="{{can.get_absolute_url}}">
                <img src="{{can.image_url}}" alt="{{can.name}} Headshot">
            </a>
          <div class="portfolio-overlay">
            <a href="{{can.get_absolute_url}}" class="center-icon"><i class="icon-line-link"></i></a>
          </div>
        </div>
        <div class="portfolio-desc">
          <h3><a href="{{can.get_absolute_url}}">{{can.first_name}} {{can.last_name}}</a></h3>
          <a href="{% url 'candidate:state' can.state|lower %}">{{can.state}}</a>{% if can.office and can.state %}<span class="middot">·</span>{% endif %}<a href="#">{{can.office}}</a>
        </div>
      </article>
    {% endfor %}
</div>
</div>
</div>
<section class="topmargin-lg bottommargin-lg">
    <div class="container clearfix">

        <div class="heading-block center">
            <h3>Get <span>Involved</span></h3>
        </div>

        <div class="">
            <form action="{% url 'mailchimp' %}" role="form" method="post" class="nobottommargin">
              {% csrf_token %}
                <div class="input-group input-group-lg divcenter" style="max-width:600px;">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="icon-user"></i></div>
                    </div>
                    <input type="text" name="first" class="form-control required" placeholder="First Name">
                </div>
                <div class="input-group input-group-lg divcenter" style="max-width:600px;  margin-top:15px">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="icon-user2"></i></div>
                    </div>
                    <input type="text" name="last" class="form-control required" placeholder="Last Name">
                </div>
                <div class="input-group input-group-lg divcenter" style="max-width:600px; margin-top:15px">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="icon-email2"></i></div>
                    </div>
                    <input type="email" name="email" class="form-control required email" placeholder="Email" required>
                    <div class="input-group-append">
                        <button type="submit" class="button nomargin button-reveal button-large button-pink tright button-full"><i class="icon-angle-right"></i><span>Join Us</span></button>
                    </div>
                </div>
            </form>
        </div>

    </div>
</section>
<div class="section">
  <div class="container clearfix topmargin-lg bottommargin-lg">
    <div class="col-12">
      <div class="center front-page">
        <h1>All <span>Women</span>.</h1>
        <h1>All <span>Political</span> Parties,</h1>
        <h1><span>Issues</span> &amp; <span>Resources</span>.</h1>
        <h1>One <span>Place</span>.</h1>
      </div>
    </div>
  </div>
</div>
<div class="container clearfix topmargin-lg bottommargin-lg">
  <div class="col_one_fourth nobottommargin">
    <div class="feature-box fbox-center fbox-light fbox-effect nobottomborder">
      <div class="fbox-icon">
        <a href="#"><i class="i-alt noborder icon-dollar"></i></a>
      </div>
      <h3>For Voters<span class="subtitle">Increase the power of women<br><br>Support individual candidates with your donation.</span></h3>
    </div>
  </div>
  <div class="col_one_fourth nobottommargin">
    <div class="feature-box fbox-center fbox-light fbox-effect nobottomborder">
      <div class="fbox-icon">
        <a href="#"><i class="i-alt noborder icon-wallet"></i></a>
      </div>
      <h3>Knowledgebase<span class="subtitle">Empower potential candidates<br><br> Access to many organizations that can help your campaign succeed.</span></h3>
    </div>
  </div>
  <div class="col_one_fourth nobottommargin">
    <div class="feature-box fbox-center fbox-light fbox-effect nobottomborder">
      <div class="fbox-icon">
        <a href="#"><i class="i-alt noborder icon-filter"></i></a>
      </div>
     <h3>Custom Reports<span class="subtitle">Information about candidates<br><br><br>A must for political consultants and other supporting organizations</span></h3>
    </div>
  </div>
  <div class="col_one_fourth nobottommargin col_last">
    <div class="feature-box fbox-center fbox-light fbox-effect nobottomborder">
      <div class="fbox-icon">
        <a href="#"><i class="i-alt noborder icon-megaphone"></i></a>
      </div>
      <h3>For Campaigns<span class="subtitle">Increase your presence<br><br><br>Build your page with compelling information about your candidate.</span></h3>
    </div>
  </div>
  <div class="clear"></div>
  <div class="line bottommargin-lg"></div>
  <div class="col_two_fifth nobottommargin">
      <img src="{% static 'images/march.jpg' %}" alt="Women's March">
  </div>
  <div class="col_three_fifth nobottommargin col_last">
    <div class="heading-block">
      <h2>Women Supported</h2>
    </div>
    <p>We support the goal of having equal representation in our highest offices of government.</p>
    <p><strong>Political Sisterhood</strong> provides access to non-partisan information on every registered women candidate for the upcoming elections. Every person who identifies as a women, regardless of political affiliation.</p>
  </div>
  <div class="clear"></div>
</div>

{% endblock %}

political_sisterhood/templates/pages/soon.html
{% extends "base.html" %}
{% load static %} {% block seo_title %} Coming Soon - Political Sisterhood {% endblock %} {% block content %}
<section id="page-title" class="page-title-mini page-title-nobg">
  <div class="container clearfix">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Coming Soon</li>
    </ol>
  </div>
</section>
<section class="themebg"></section>
{% include 'includes/coming_soon.html' %}
{% endblock %}