config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.views.generic.base import RedirectView
from political_sisterhood.pages.views import PageDetailView
from political_sisterhood.issue.views import IssueAutocomplete
from political_sisterhood.search.views import MySearchView
from .views import HomePage, Mailchimp, ContactUs

urlpatterns = [
    url(r'^$', HomePage.as_view(), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^news/$', TemplateView.as_view(template_name='pages/news.html'), name='news'),
    url(r'^contact-us/$', ContactUs.as_view(), name='contact'),
    url(r'^coming-soon/$', TemplateView.as_view(template_name='pages/soon.html'), name='coming-soon'),
    url(r'^issue-ac/', IssueAutocomplete.as_view(), name="issue-autocomplete"),
    # UTILITY VIEWS
    url(r'mailchimp-signup/$', Mailchimp, name='mailchimp'),
    url(r'^report_builder/', include('report_builder.urls')),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^profile/', include('political_sisterhood.users.urls', namespace='users')),
    url(r'^accounts/social/connections/$', RedirectView.as_view(pattern_name='users:redirect', permanent=True)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^candidates/', include('political_sisterhood.candidate.urls', namespace='candidate')),
    url(r'^races/', include('political_sisterhood.races.urls', namespace='races')),
    url(r'^jobs/', include('political_sisterhood.jobs.urls', namespace='jobs')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^admin/dynamic_raw_id/', include('dynamic_raw_id.urls')),
    url(r'^search/?$', MySearchView.as_view(), name='search'),

    # Your stuff: custom urls includes go here
    url(r'^(?P<slug>[\w.@+-]+)/$', PageDetailView.as_view()),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

political_sisterhood/jobs/urls.py
from django.conf.urls import include, url
from .views import JobsAll, JobsPost

app_name = 'jobs'

urlpatterns = [
    url(r'^$',
        JobsAll.as_view(),
        name='all'
    ),
    url(r'post/$',
        JobsPost.as_view(),
        name='post'
    ),
]

political_sisterhood/races/urls.py
from django.conf.urls import url
from .views import RaceAdd

app_name = 'races'

urlpatterns = [
    url(r'^add/$',
        RaceAdd.as_view(),
        name='all'
    ),

]

political_sisterhood/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^settings/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

political_sisterhood/candidate/models.py
from django.db import models
from model_utils.fields import StatusField
from model_utils import FieldTracker
from django.urls import reverse
from django.utils.functional import cached_property
from ckeditor.fields import RichTextField
from model_utils import Choices
import hashlib
from templated_email import send_templated_mail
from datetime import datetime
from django.template.defaultfilters import slugify
from django.contrib.sites.models import Site
from django.utils import timezone
from .constants import IDENTIFIER, OPT_OPTIONS, STATES, PARTY
import geocoder
import logging

logger = logging.getLogger(__name__)
# Create your models here.


class Candidate(models.Model):
    IDENT = IDENTIFIER
    OPT_OPTIONS = OPT_OPTIONS
    STATES = STATES
    PARTY = PARTY
    active = models.BooleanField(default=True)
    approval_status = Choices(('Approved'), ('Pending'),)
    approval = StatusField(choices_name='approval_status', db_index=True)
    man = models.BooleanField(default=False)
    unique_identifier1 = StatusField(choices_name='IDENT',
                                     blank=True, null=True, default=None)
    unique_identifier2 = StatusField(choices_name='IDENT',
                                     blank=True, null=True, default=None)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    full = models.CharField(max_length=1024, blank=True, null=True, help_text="Only use if different than\
                                                                               first and last combined.")
    email = models.EmailField(max_length=255, blank=True)
    image = models.ImageField(blank=True, null=True, verbose_name="Headshot")
    image_attribution = models.CharField(max_length=1024,
                                         blank=True, null=True)
    filing_number = models.CharField(max_length=1024,
                                     blank=True, null=True)

    state = StatusField(choices_name='STATES', db_index=True)
    race_name = models.CharField(max_length=1024, blank=True,
                                 null=True,
                                 help_text="Only internal field, must populate actual race")

    bio = RichTextField(blank=True, max_length=4000)
    # Campaign Office Info
    phone = models.CharField(max_length=255, blank=True, verbose_name="Campaign Phone")
    campaign_name = models.CharField(max_length=1024, blank=True, verbose_name="Campaign HQ Name")
    campaign_street = models.CharField(max_length=255, blank=True, verbose_name="Campaign HQ Street")
    campaign_street2 = models.CharField(max_length=255, blank=True, verbose_name="Campaign HQ Street 2 (if applicable)")
    campaign_city = models.CharField(max_length=255, blank=True, verbose_name="Campaign HQ City")
    campaign_zip = models.CharField(max_length=9, blank=True, verbose_name="Campaign HQ Zip/Postal Code")
    campaign_lat = models.CharField(max_length=255, blank=True, null=True)
    campaign_long = models.CharField(max_length=255, blank=True, null=True)

    # Social Accounts
    facebook = models.CharField(max_length=1064, blank=True)
    facebook_follower = models.IntegerField(null=True, blank=True)
    twitter = models.CharField(max_length=1064, blank=True)
    twitter_follower = models.IntegerField(null=True, blank=True)
    linkedin = models.CharField(max_length=1064, blank=True)
    website = models.CharField(max_length=1064, blank=True)

    # Issues
    issue1 = models.CharField(max_length=1064, blank=True, null=True)
    issue1_detail = models.TextField(max_length=280,
                                     blank=True)
    issue2 = models.CharField(max_length=1064, blank=True, null=True)
    issue2_detail = models.TextField(max_length=280,
                                     blank=True)
    issue3 = models.CharField(max_length=1064, blank=True, null=True)
    issue3_detail = models.TextField(max_length=280,
                                     blank=True)

    # Candidate Info
    party = StatusField(choices_name='PARTY', db_index=True)
    college = models.ForeignKey('College', on_delete=models.CASCADE, null=True, blank=True)
    phone = models.CharField(max_length=255, blank=True)
    ethnicity = models.ManyToManyField('Ethnicity', blank=True)
    marginalized = StatusField(choices_name='OPT_OPTIONS', blank=True, null=True)
    lgbtq = StatusField(choices_name='OPT_OPTIONS', blank=True, null=True)
    homepage = models.BooleanField(default=False)
    referral = models.CharField(max_length=1024, blank=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=1024)

    tracker = FieldTracker()

    def __str__(self):
        return "{}".format(self.name)

    @property
    def name(self):
        if self.first_name and self.last_name:
            return "{} {}".format(self.first_name, self.last_name)

    @property
    def full_name(self):
        if self.full:
            return self.full
        return self.name

    @property
    def race(self):
        if self.candidates:
            for race in self.candidates.all():
                return race

    @property
    def address(self):
        return "{} {}".format(self.campaign_street, self.campaign_street2)

    @property
    def full_address(self):
        full_addres = ""
        if self.campaign_street:
            full_addres += "{} ".format(self.campaign_street)
        if self.campaign_street2:
            full_addres += "{} ".format(self.campaign_street2)
        if self.campaign_city:
            full_addres += "{} ".format(self.campaign_city)
        if self.state:
            full_addres += "{} ".format(self.state)
        if self.campaign_zip:
            full_addres += "{} ".format(self.campaign_zip)
        return full_addres

    @property
    def approved(self):
        if self.approval == 'Approved':
            return True
        return False

    @property
    def identifier(self):
        if self.unique_identifier1 and self.unique_identifier2:
            return "{} & {}".format(self.unique_identifier1, self.unique_identifier2)
        if self.unique_identifier1:
            return self.unique_identifier1
        if self.unique_identifier2:
            return self.unique_identifier2
        return None

    @property
    def follow(self):
        if self.facebook or self.twitter or self.linkedin or self.website:
            return True
        return False

    def image_url(self):
        if self.image:
            return self.image.url
        return "/static/images/missingLogo.jpg"

    def hq(self):
        if self.campaign_street or self.campaign_city or self.campaign_zip:
            return True
        return False

    @property
    def map(self):
        if self.campaign_lat and self.campaign_long:
            return True
        return False

    def get_absolute_url(self):
        return reverse('candidate:detail', kwargs={
            'state': self.state.lower(),
            'slug': self.slug
        })

    def edit_url(self):
        return reverse('admin:%s_%s_change' % (self._meta.app_label,
                                               self._meta.model_name),
                       args=[self.id])

    def save(self, *args, **kwargs):
        if not self.slug:
            slug_me = "{}-{}".format(self.first_name, self.last_name)
            self.full = "{} {}".format(self.first_name, self.last_name)
            slug = slugify(slug_me)
            i = 1
            while Candidate.objects.filter(slug=slug).exists():
                slug = "{}{}".format(slugify(slug_me),i)
                i += 1
            self.slug = slug
        if not self.full:
            self.full = self.full_name
        if self.campaign_street:
            result = geocoder.google(self.full_address)
            if result:
                self.campaign_lat = result.lat
                self.campaign_long = result.lng
            else:
                logger.error("Issue with GeoCoding: {}".format(self.id))
        super(Candidate, self).save(*args, **kwargs)


class College(models.Model):
    name = models.CharField(max_length=1064, blank=True)

    def __str__(self):
        return self.name


class Ethnicity(models.Model):
    name = models.CharField(max_length=1064, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Ethnicities"
        ordering = ['name']


class CandidateReferral(models.Model):
    name = models.CharField(max_length=1025)

    def __str__(self):
        return self.name

    @property
    def url(self):
        name = slugify(self.name)
        return "https://www.politicalsisterhood.org/candidates/create/?ref={}".format(name)

    class Meta:
        verbose_name_plural = "Candidate Referral Source"


class CandidateUpdate(models.Model):
    email = models.CharField(max_length=1025)
    first_name = models.CharField(max_length=1025)
    last_name = models.CharField(max_length=1025)
    note = models.TextField(blank=True)
    updated = models.DateTimeField(null=True, blank=True)
    candidate = models.ForeignKey('Candidate', on_delete=models.CASCADE, null=True)

    def save(self, *args, **kwargs):
        self.updated = datetime.now()
        super(CandidateUpdate, self).save(*args, **kwargs)

    @property
    def name(self):
        return "{} {}".format(self.first_name, self.last_name)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Candidate Update"


class CandidateInvite(models.Model):
    email = models.CharField(max_length=1025)
    first_name = models.CharField(max_length=1025)
    last_name = models.CharField(max_length=1025)
    md5_email = models.CharField(max_length=32, editable=False)
    used = models.BooleanField(default=False)
    emailed = models.DateTimeField(null=True, blank=True)
    candidate = models.ForeignKey('Candidate', on_delete=models.SET_NULL, null=True)

political_sisterhood/races/models.py
from django.db import models
from model_utils import Choices
from model_utils.fields import StatusField
from political_sisterhood.candidate.models import Candidate
from ckeditor.fields import RichTextField
from political_sisterhood.candidate.constants import STATES
# Create your models here.

class State(models.Model):
    STATES = STATES
    state = StatusField(choices_name='STATES')
    seal = models.FileField(blank=True, null=True)
    website = models.CharField(max_length=1024, blank=True)
    bio = RichTextField(blank=True)
    senate_compensation = models.CharField(max_length=1024, blank=True)
    senate_requirements = models.CharField(max_length=1024, blank=True)
    house_compensation = models.CharField(max_length=1024, blank=True)
    house_requirements = models.CharField(max_length=1024, blank=True)
    legislative_benefits = models.CharField(max_length=1024, blank=True)
    salary_schedule = models.CharField(max_length=1024, blank=True)
    declaration_candidacy = models.CharField(max_length=1024, blank=True)

    @property
    def seal_url(self):
        if self.seal:
            return self.seal.url
        return None

    @property
    def available(self):
        return Race.objects.filter(state=self).count()

    @property
    def women(self):
        return RaceEntry.objects.filter(race_id=self.id).count()

    @property
    def men(self):
        return self.available - RaceEntry.objects.filter(race_id=self.id).distinct('race').count()

    def __str__(self):
        return self.get_state_display()

    class Meta:
        ordering = ['state']


class Race(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE, related_name="states")
    district = models.CharField(max_length=255, blank=True)
    other = models.CharField(max_length=255, blank=True,
                             help_text="If there is another descriptor for the race")
    RACE = Choices('US Senate', 'US House', 'Governor',
                   'State House', 'State Senate', 'State Assembly')
    race_type = StatusField(choices_name='RACE')
    filing_date = models.DateField(blank=True, null=True)
    primary_date = models.DateField(blank=True, null=True)
    caucus_date = models.DateField(blank=True, null=True)
    election_date = models.DateField(blank=True, null=True)

    @property
    def title(self):
        if self.district:
            return "District {} - {}".format(self.district, self.state)
        elif self.other:
            return "{} - {}".format(self.other, self.state)
        elif self.race_type == "Governor":
            return "Governor - {}".format(self.state)
        elif self.race_type == 'Senate':
            return "Senate {}".format(self.state)
        else:
            return "{}".format(self.state)

    def __str__(self):
        return self.title

    @property
    def int_district(self):
        return int(self.district)


    @property
    def open(self):
        if self.races:
            return False
        return True

    class Meta:
        ordering = ['pk']


class RaceEntry(models.Model):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='candidates')
    race = models.ForeignKey(Race, on_delete=models.CASCADE, related_name="races")
    current = models.BooleanField(default=False)

    @property
    def deep(self):
        if self.race.race_type == 'State House' or\
           self.race.race_type == 'State Senate' or\
           self.race.race_type == 'State Assembly':
            return True
        return False

    @property
    def race_type(self):
        return self.race.race_type

    @property
    def title(self):
        return self.race.title

political_sisterhood/search/models.py
# empty

political_sisterhood/pages/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from .models import Page
# Create your views here.

class PageDetailView(DetailView):
    model = Page
    template_name = 'pages/detail.html'
    slug_url_kwarg = 'slug'

political_sisterhood/templates/candidate/all.html
{% extends 'base.html' %}
{% load static i18n compress %}

{% block seo_title %}
Candidate Reports - Political Sisterhood
{% endblock %}

{% block content %}
<section id="page-title" class="page-title page-title-nobg">
  <div class="container clearfix">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Candidate Reports</li>
    </ol>
  </div>
</section>

<section class="themebg"></section>
<section class="topmargin-lg bottommargin-lg" style="">
  <div class="container-fluid center clearfix">
    <div class="heading-block">
      <h1>Candidate Reports</h1>
      <span>Over {{candidate}} registered women candidates for Federal and State legislative branches for the United
States.</span>
      <div class="clear"></div>
    </div>
    <div class="col_one_third nobottommargin bounceIn animated" data-animate="bounceIn">
      <div class="counter counter-large counter-lined"><span data-from="0" data-to="50" data-refresh-interval="20" data-speed="2000">{{STATES}}</span></div>
      <h5>States</h5>
    </div>
    <div class="col_one_third nobottommargin bounceIn animated" data-animate="bounceIn" data-delay="200">
      <div class="counter counter-large counter-lined"><span data-from="0" data-to="{{CANDIDATE}}" data-refresh-interval="10" data-speed="2000">{{CANDIDATE}}</span></div>
      <h5>Women Candidates</h5>
    </div>
    <div class="col_one_third col_last nobottommargin bounceIn animated" data-animate="bounceIn" data-delay="400">
      <div class="counter counter-large counter-lined"><span data-from="0" data-to="{{RACES}}" data-refresh-interval="13" data-speed="3000">{{RACES}}</span></div>
      <h5>Open Seats</h5>
    </div>
  </div>
<span id="search"></span>
</section>
<section class="toppadding-lg bottompadding-sm bottommargin-lg report-about" style="">
  <div class="container center clearfix">
    <div class="row">
      <div class="col-sm-12 center bottompadding-sm">
          <h3>Our candidate portal allows you to search for and find any registered woman candidate.</h3>
        </div>
    </div>
  </div>
</section>

{% include 'search/search_section.html' %}
{% endblock content %}
{% block extra_js %}
<link href="{% static 'maps/jsmaps.css' %}" rel="stylesheet" type="text/css" />
<script src="{% static 'maps/jsmaps-libs.js' %}" type="text/javascript"></script>
<script src="{% static 'maps/jsmaps-panzoom.js' %}"></script>
<script src="{% static 'maps/jsmaps.min.js' %}" type="text/javascript"></script>
<script src="{% static 'maps/usa.js' %}" type="text/javascript"></script>
<script type="text/javascript">
$(function() {

  $('#usa-map').JSMaps({
    map: 'usa',
    onStateClick: function(data) {
      $('#id_state').val(data.abbreviation); // Select the option with the abbr
      $('#id_state').trigger('change'); // Notify any JS components that the value changed

    }
  });

});

</script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
<script type="text/javascript">
$('#id_party').select2({
  placeholder: 'Select a political party',
  width: '100%',
});
$('#id_college').select2({
  placeholder: 'Select an institution',
  width: '100%',
});
$('#id_state').select2({
  placeholder: 'Select a state',
  width: '100%',
});
$('#id_issues').select2({
  placeholder: 'Select an issue',
  width: '100%',
});
$('#id_race').select2({
    placeholder: 'Select a race',
    width: '100%',
});
$('#id_race_type').select2({
    placeholder: 'Select a race type',
    width: '100%',
});
</script>
<script>
    var hash = window.location.hash
    if (hash === "#search") {
      $('html,body').animate({
        scrollTop: $("#search").position().top + 470
    }, 2000);
    }
</script>
{% endblock %}

political_sisterhood/templates/candidate/create.html
{% extends "base.html" %}
{% load crispy_forms_tags static %}

{% block title %}Create New Candidate{% endblock %}

{% block content %}
<style>
.django-ckeditor-widget {
    display: block !important;
}
.cke {width: 100% !important}
</style>
<section id="page-title" class="page-title-mini page-title-nobg">
  <div class="container clearfix">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'candidate:all' %}">Candidate Reports</a></li>
      {% block breadcrumbs %}
      <li class="breadcrumb-item active" aria-current="page">Create a New Candidate</li>
      {% endblock %}
    </ol>
  </div>
</section>
<section class="themebg"></section>
<section id="content" style="margin-bottom: 0px;">
  <div class="container clear-bottommargin clearfix topmargin-sm bottommargin-sm">
        {% block hello %}
        <p>The Political Sisterhood registry is free to candidates who meet the eligibility requirements listed below:
            <ul>
              <li>Officially registered (must providing filing information) for political elections in the United States.
              For 2018, this includes the U.S. and individual State congressional elections, and the Governor races.</li>
              <li>Identify as a woman</li>
            </ul>
        Adding candidate information to our national registry will automatically increase the visibility and support of your campaign. Candidates
        will remain on the registry until November 7th, 2018 unless no longer an active candidate. Election winners will remain in the Registry.<br><br>
        Please complete the form and submit for review and approval. Once approved, we will notify you and your page has been added to the Registry and appears on the website. </p>
        {% endblock %}
        {{form.error}}
        <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {% block hidden_fields %}
        <input type="hidden" value="{{referral}}" name="ref" id="ref">
        {% endblock %}
        {% crispy form %}

        <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
        {{form.media}}
      </form>
    </div>
</section>
{% endblock %}

political_sisterhood/templates/candidate/list.html
{% extends 'base.html' %}
{% block seo_title %}
Candidate List - Political Sisterhood
{% endblock %}
{% block content %}

{% endblock %}

political_sisterhood/templates/candidate/paywall.html
{% extends 'base.html' %}
{% load static %}
{% block seo_title %}
Next Steps - Political Sisterhood
{% endblock %}

{% block content %}

<section id="page-title" class="page-title-mini page-title-nobg">
  <div class="container clearfix">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'candidate:all' %}">Candidate Reports</a></li>
      <li class="breadcrumb-item active" aria-current="page">Next Steps</li>
    </ol>
  </div>
</section>
<section class="themebg"></section>
<section id="content" style="margin: 250px 0;">
  <div class="container clear-bottommargin clearfix toppadding-sm bottompadding-sm">
    <div class="heading-block center">
      <h2 class="normal-case">You've hit your limit for free candidate views.</h2>
      <p>To continue, please <a href="/accounts/login/">login</a> or <a href="/accounts/signup/">register</a>.</p>
    </div>
  </div>
</section>
{% endblock %}

political_sisterhood/templates/candidate/update.html
{% extends 'candidate/create.html' %}
{% block breadcrumbs %}
    <li class="breadcrumb-item active" aria-current="page">Update Candidate</li>
{% endblock %}
{% block hello %}
    <p>
        {% if contact %}
        <strong>{{contact.name}},</strong><br>
        {% endif %}
        Data from this form will be included in the complete list of women candidates for the 2018 U.S. federal congressional elections.  The website is live and will continue to be updated.  Please use the unique identifier question as a way to bring people to you - this will be on the site, and we will target groups that are related to the identifier - ie dog lover - could go to rescue groups, animal rights, etc.
    </p>
{% endblock %}
{% block hidden_fields %}
{% endblock %}