config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.views.generic.base import RedirectView
from political_sisterhood.pages.views import PageDetailView
from political_sisterhood.issue.views import IssueAutocomplete
from political_sisterhood.search.views import MySearchView
from .views import HomePage, Mailchimp, ContactUs

urlpatterns = [
    url(r'^$', HomePage.as_view(), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^news/$', TemplateView.as_view(template_name='pages/news.html'), name='news'),
    url(r'^contact-us/$', ContactUs.as_view(), name='contact'),
    url(r'^coming-soon/$', TemplateView.as_view(template_name='pages/soon.html'), name='coming-soon'),
    url(r'^issue-ac/', IssueAutocomplete.as_view(), name="issue-autocomplete"),
    # UTILITY VIEWS
    url(r'mailchimp-signup/$', Mailchimp, name='mailchimp'),
    url(r'^report_builder/', include('report_builder.urls')),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^profile/', include('political_sisterhood.users.urls', namespace='users')),
    url(r'^accounts/social/connections/$', RedirectView.as_view(pattern_name='users:redirect', permanent=True)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^candidates/', include('political_sisterhood.candidate.urls', namespace='candidate')),
    url(r'^races/', include('political_sisterhood.races.urls', namespace='races')),
    url(r'^jobs/', include('political_sisterhood.jobs.urls', namespace='jobs')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^admin/dynamic_raw_id/', include('dynamic_raw_id.urls')),
    url(r'^search/?$', MySearchView.as_view(), name='search'),

    # Your stuff: custom urls includes go here
    url(r'^(?P<slug>[\w.@+-]+)/$', PageDetailView.as_view()),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

political_sisterhood/jobs/urls.py
from django.conf.urls import include, url
from .views import JobsAll, JobsPost

app_name = 'jobs'

urlpatterns = [
    url(r'^$',
        JobsAll.as_view(),
        name='all'
    ),
    url(r'post/$',
        JobsPost.as_view(),
        name='post'
    ),
]

political_sisterhood/races/urls.py
from django.conf.urls import url
from .views import RaceAdd

app_name = 'races'

urlpatterns = [
    url(r'^add/$',
        RaceAdd.as_view(),
        name='all'
    ),

]

political_sisterhood/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^settings/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

political_sisterhood/pages/models.py
from django.db import models
from ckeditor.fields import RichTextField


# Create your models here.
class Page(models.Model):
    title = models.CharField(max_length=255)
    content = RichTextField()
    slug = models.SlugField()

    def __str__(self):
        return self.title

political_sisterhood/search/models.py
# empty

political_sisterhood/candidate/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.views.generic import DetailView, CreateView,\
                                 TemplateView, UpdateView,\
                                 ListView, RedirectView
from django.core.mail import send_mail
from templated_email import send_templated_mail
from django.contrib import messages
from .models import Candidate, CandidateInvite, College, CandidateUpdate
from political_sisterhood.issue.models import CandidateIssue
from haystack.generic_views import SearchView as BaseFacetedSearchView
from political_sisterhood.races.models import State, Race
import logging
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .forms import CandidateForm
from political_sisterhood.search.forms import SearchForm
from haystack.query import SearchQuerySet, EmptySearchQuerySet, SQ
from haystack.inputs import AutoQuery
import urllib.parse as urlparse
logger = logging.getLogger(__name__)
# Create your views here.


def sendingEmail(candidate, new_data):
    candidate = Candidate.objects.get(id=candidate)
    from django.core import serializers
    try:
        send_templated_mail(
            template_name='updated',
            from_email="Political Sisterhood <info@politicalsisterhood.org>",
            recipient_list=['chris@politicalsisterhood.com',
                            'susan@politicalsisterhood.com'],
            context={
                'name': candidate.full_name,
                'url': candidate.get_absolute_url(),
                'candidate': candidate,
                'instance': new_data
            }
        )
    except Exception as e:
        logger.error(e)


class AllCandidates(BaseFacetedSearchView):
    template_name = "candidate/all.html"
    facet_fields= ['party']
    form_class = SearchForm
    paginate_by = 12
    paginate_orphans = 2

    # All CHANGES NEED TO BE DONE IN SEARCH/VIEWS AND CANDIDATE/VIEWS
    def get_queryset(self):
        queryset = SearchQuerySet().filter(active=True).order_by('first_name')
        # further filter queryset based on some set of criteria
        party = self.request.GET.getlist('party', '')
        party_or = ""
        college = self.request.GET.getlist('college', '')
        college_or = ""
        state = self.request.GET.getlist('state', '')
        state_or = ""
        issues = self.request.GET.getlist('issues', '')
        issues_or = ""
        race = self.request.GET.getlist('race', '')
        race_or = ""
        race_type = self.request.GET.getlist('race_type', '')
        race_type_or = ""
        women = self.request.GET.get('women', '')
        q = self.request.GET.get('q', '')
        page = self.request.GET.get('page', '')
        search = ''.join(party) + q + page
        if search == "":
            search = "null"
        if party:
            for facet in party:
                party_or += 'party: "%s"' % (facet)
            queryset = queryset.narrow(party_or)
        if college:
            for facet in college:
                college_or += 'college: "%s"' % (facet)
            queryset = queryset.narrow(college_or)
        if state:
            for facet in state:
                state_or += 'state: "%s"' % (facet)
            queryset = queryset.narrow(state_or)
        if issues:
            for facet in issues:
                issues_or += 'issues: "%s"' % (facet)
            queryset = queryset.narrow(issues_or)
        if race:
            for facet in race:
                race_or += 'race: "%s"' % (facet)
            queryset = queryset.narrow(race_or)
        if race_type:
            for facet in race_type:
                race_type_or += 'race_type: "%s"' % (facet)
            queryset = queryset.narrow(race_type_or)
        if q:
            queryset = queryset.filter(SQ(text=AutoQuery(q))|SQ(title=AutoQuery(q)))
        if women:
            queryset = queryset.filter(women=True)
        return queryset

    def form_valid(self, form):
        context = self.get_context_data(**{
            self.form_name: form,
            'object_list': self.get_queryset()
        })
        return self.render_to_response(context)

    def form_invalid(self, form):
        context = self.get_context_data(**{
            self.form_name: form,
            'object_list': self.get_queryset()
        })
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q','')
        context['party'] = self.request.GET.getlist('party', '')
        context['college'] = self.request.GET.getlist('college', '')
        context['state'] = self.request.GET.getlist('state', '')
        context['issues'] = self.request.GET.getlist('issues', '')
        women = self.request.GET.get('women', '')
        if women == True or women == 'on':
            context['women'] = True
        context['race_type'] = self.request.GET.getlist('race_type', '')
        return context


class CandidateView(DetailView):
    model = Candidate
    template_name = "candidate/detail.html"

    def dispatch(self, *args, **kwargs):
        user = self.request.user.is_authenticated
        if 'visited' in self.request.session:
            visits = self.request.session['visited']
        else:
            visits = None
        if not user:
            if visits and len(visits) > 3:
                return redirect(reverse('candidate:paywall'))
            visited = []
            candidate = self.get_object().id
            if visits:
                visited.extend(visits)
                if not candidate in visits:
                    visited.append(candidate)
            else:
                visited.append(candidate)
            self.request.session['visited'] = visited
        return super().dispatch(*args, **kwargs)

    def get_object(self):
        slug = self.kwargs['slug']
        candidate = Candidate.objects.get(slug=slug)
        return candidate

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['approved'] = False
        if self.request.GET.get('approved') == 'pending':
            context['approved'] = True
        elif self.get_object().approved:
            context['approved'] = True
        return context


class StateListView(ListView):
    model = Candidate
    template_name = "state/list.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        state =State.objects.get(state=self.kwargs['state'].upper())
        data['object'] = state
        return data

    def get_queryset(self):
        state = Candidate.objects.filter(state=self.kwargs['state'])
        return state


class UpdateCandidateInvite(UpdateView):
    # specify a custom ModelForm
    form_class = CandidateForm
    template_name = "candidate/update.html"

    def get_object(self, queryset=None):
        # get the existing object or created a new one
        candidate = get_object_or_404(CandidateInvite, md5_email=self.kwargs['hash'])
        if candidate.candidate:
            obj = Candidate.objects.get(id=candidate.candidate.id)
            CandidateInvite.objects.filter(md5_email=self.kwargs['hash']).update(candidate=obj)
        else:
            obj = None
        return obj

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['contact'] = CandidateInvite.objects.get(md5_email=self.kwargs['hash'])
        return data

    def form_valid(self, form):
        instance = form.save(commit=False)
        try:
            sendingEmail(instance.id, instance)
        except Exception as e:
            logger.error(e)
        instance.save()
        try:
            CandidateInvite.objects.filter(md5_email=self.kwargs['hash']).update(used=True)
            issue1, create = CandidateIssue.objects.get_or_create(candidate=instance,
                                                                  issue=form.cleaned_data.get('issue1'),
                                                                  desc=form.cleaned_data.get('issue1_detail'))
            issue2, created = CandidateIssue.objects.get_or_create(candidate=instance,
                                                                   issue=form.cleaned_data.get('issue2'),
                                                                   desc=form.cleaned_data.get('issue2_detail'))
            issue3, created = CandidateIssue.objects.get_or_create(candidate=instance,
                                                                   issue=form.cleaned_data.get('issue3'),
                                                                   desc=form.cleaned_data.get('issue3_detail'))
            college, create = College.objects.get_or_create(name=form.cleaned_data['college_free'])
            Candidate.objects.filter(id=instance.id).update(issue1=issue1.issue_num,
                                                            issue2=issue2.issue_num,
                                                            issue3=issue3.issue_num,
                                                            race_name=form.cleaned_data.get('race_name'),
                                                            college=college, approval="Pending")
            try:
                CandidateUpdate.objects.create(email=form.cleaned_data.get('update_email'),
                                               first_name=form.cleaned_data.get('update_first_name'),
                                               last_name=form.cleaned_data.get('update_last_name'),
                                               note=form.cleaned_data.get('update_note', ''),
                                               candidate=instance)
            except Exception as e:
                logger.error(e)
        except Exception as e:

political_sisterhood/issue/views.py
from dal import autocomplete
from django.utils.translation import ugettext as _
from django import http
from .models import Issue
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator


import logging

logger = logging.getLogger(__name__)

@method_decorator(csrf_exempt, name='dispatch')
class IssueAutocomplete(autocomplete.Select2QuerySetView):
    create_field = "name"

    def post(self, request):
        text = request.POST.get('text', None)

        if text is None:
            return http.HttpResponseBadRequest()

        parent = Issue.objects.get(name="Other")
        try:
            result, create = Issue.objects.get_or_create(name=text, parent=parent)
        except Exception as e:
            logger.error(e)

        return http.JsonResponse({
            'id': result.pk,
            'text': self.get_result_label(result),
        })

    def get_queryset(self):
        qs = Issue.objects.filter(parent__isnull=True)
        if self.q:
            qs = qs.filter(name__istartswith=self.q)
        return qs

    def get_create_option(self, context, q):
        """Form the correct create_option to append to results."""
        create_option = []
        display_create_option = False
        if self.create_field and q:
            display_create_option = True
            # Don't offer to create a new option if a
            # case-insensitive) identical one already exists
            existing_options = (self.get_result_label(result).lower()
                                for result in context['object_list'])
            if q.lower() in existing_options:
                display_create_option = False
        if display_create_option:
            create_option = [{
                'id': q,
                'text': _('Create "%(new_value)s"') % {'new_value': q},
                'create_id': True,
            }]
        return create_option

political_sisterhood/jobs/views.py
from django.shortcuts import render
from django.views.generic import DetailView, CreateView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class JobsAll(TemplateView):
    template_name = "jobs/all.html"

class JobsPost(LoginRequiredMixin, TemplateView):
    template_name = "jobs/post.html"

political_sisterhood/pages/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from .models import Page
# Create your views here.

class PageDetailView(DetailView):
    model = Page
    template_name = 'pages/detail.html'
    slug_url_kwarg = 'slug'

political_sisterhood/races/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import Race
from political_sisterhood.candidate.models import Candidate
from braces import views
import logging
logger = logging.getLogger(__name__)
# Create your views here.


class RaceAdd(views.StaffuserRequiredMixin, TemplateView):
    template_name = "races/add.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['races'] = Race.objects.select_related('state').all()
        data['candidates'] = Candidate.objects.all()
        return data

    def post(self, request, **kwargs):
        logger.info(request.POST)

political_sisterhood/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<section id="content" style="margin-bottom: 0px;">

      <div class="content-wrap">

        <div class="container clearfix">

          <div class="row clearfix">

            <div class="col-sm-9">


              <div class="heading-block noborder">
                <h3>{{ object.name|default_if_none:"" }}</h3>
                <span>Your Political Sisterhood Profile</span>
              </div>

              <div class="clear"></div>

              <div class="row clearfix">

                <div class="col-md-12">
                  {% comment %}
                  <div class="tabs tabs-alt clearfix ui-tabs ui-widget ui-widget-content ui-corner-all" id="tabs-profile">
                    <ul class="tab-nav clearfix ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all" role="tablist">
                      <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab" tabindex="0" aria-controls="tab-payments" aria-labelledby="ui-id-1" aria-selected="true" aria-expanded="true"><a href="#tab-payments" class="ui-tabs-anchor" role="presentation" tabindex="-1" id="ui-id-1"><i class="icon-dollar"></i>Payments</a></li>
                      <li class="ui-state-default ui-corner-top" role="tab" tabindex="-1" aria-controls="tab-candidates" aria-labelledby="ui-id-2" aria-selected="false" aria-expanded="false"><a href="#tab-candidates" class="ui-tabs-anchor" role="presentation" tabindex="-1" id="ui-id-2"><i class="icon-user2"></i>Candidates</a></li>
                      <li class="ui-state-default ui-corner-top" role="tab" tabindex="-1" aria-controls="tab-reports" aria-labelledby="ui-id-3" aria-selected="false" aria-expanded="false"><a href="#tab-reports" class="ui-tabs-anchor" role="presentation" tabindex="-1" id="ui-id-3"><i class="icon-filter"></i>Reports</a></li>
                    </ul>

                    <div class="tab-container">

                      <div class="tab-content clearfix ui-tabs-panel ui-widget-content ui-corner-bottom" id="tab-payments" aria-labelledby="ui-id-1" role="tabpanel" aria-hidden="false" style="display: block;">

                        <p class="">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium harum ea quo! Nulla fugiat earum, sed corporis amet iste non, id facilis dolorum, suscipit, deleniti ea. Nobis, temporibus magnam doloribus. Reprehenderit necessitatibus esse dolor tempora ea unde, itaque odit. Quos.</p>

                        <div class="table-responsive">
                          <table class="table table-bordered table-striped">
                            <colgroup>
                            <col class="col-xs-1">
                            <col class="col-xs-5">
                            <col class="col-xs-2">
                            </colgroup>
                            <thead>
                            <tr>
                              <th>Time</th>
                              <th>Activity</th>
                              <th>Amount</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                              <td>
                              <code>3/23/2018</code>
                              </td>
                              <td>Purchased Credits</td>
                              <td>$41.23</td>
                            </tr>
                            </tbody>
                          </table>
                        </div>

                      </div>
                      <div class="tab-content clearfix ui-tabs-panel ui-widget-content ui-corner-bottom" id="tab-candidates" aria-labelledby="ui-id-2" role="tabpanel" aria-hidden="true" style="display: none;">

                    <div class="row topmargin-sm">
                          <div class="col-md-3 col-sm-6 bottommargin">

                            <div class="team">
                              <div class="team-image">
                                <img src="http://canvashtml-cdn.semicolonweb.com/images/team/3.jpg" alt="John Doe">
                              </div>
                              <div class="team-desc">
                                <div class="team-title"><h4>John Doe</h4><span>CEO</span></div>
                                <a href="#" class="social-icon inline-block si-small si-light si-rounded si-facebook">
                                  <i class="icon-facebook"></i>
                                  <i class="icon-facebook"></i>
                                </a>
                                <a href="#" class="social-icon inline-block si-small si-light si-rounded si-twitter">
                                  <i class="icon-twitter"></i>
                                  <i class="icon-twitter"></i>
                                </a>
                                <a href="#" class="social-icon inline-block si-small si-light si-rounded si-gplus">
                                  <i class="icon-gplus"></i>
                                  <i class="icon-gplus"></i>
                                </a>
                              </div>
                            </div>

                          </div>

                          <div class="col-md-3 col-sm-6 bottommargin">

                            <div class="team">
                              <div class="team-image">
                                <img src="http://canvashtml-cdn.semicolonweb.com/images/team/2.jpg" alt="Josh Clark">
                              </div>
                              <div class="team-desc">
                                <div class="team-title"><h4>Josh Clark</h4><span>Co-Founder</span></div>
                                <a href="#" class="social-icon inline-block si-small si-light si-rounded si-facebook">
                                  <i class="icon-facebook"></i>
                                  <i class="icon-facebook"></i>
                                </a>
                                <a href="#" class="social-icon inline-block si-small si-light si-rounded si-twitter">
                                  <i class="icon-twitter"></i>
                                  <i class="icon-twitter"></i>
                                </a>
                                <a href="#" class="social-icon inline-block si-small si-light si-rounded si-gplus">
                                  <i class="icon-gplus"></i>
                                  <i class="icon-gplus"></i>
                                </a>
                              </div>
                            </div>

                          </div>

                          <div class="col-md-3 col-sm-6 bottommargin">

                            <div class="team">
                              <div class="team-image">
                                <img src="http://canvashtml-cdn.semicolonweb.com/images/team/8.jpg" alt="Mary Jane">
                              </div>
                              <div class="team-desc">
                                <div class="team-title"><h4>Mary Jane</h4><span>Sales</span></div>
                                <a href="#" class="social-icon inline-block si-small si-light si-rounded si-facebook">
                                  <i class="icon-facebook"></i>
                                  <i class="icon-facebook"></i>
                                </a>
                                <a href="#" class="social-icon inline-block si-small si-light si-rounded si-twitter">
                                  <i class="icon-twitter"></i>
                                  <i class="icon-twitter"></i>
                                </a>
                                <a href="#" class="social-icon inline-block si-small si-light si-rounded si-gplus">
                                  <i class="icon-gplus"></i>
                                  <i class="icon-gplus"></i>
                                </a>
                              </div>
                            </div>

                          </div>

                          <div class="col-md-3 col-sm-6">

                            <div class="team">
                              <div class="team-image">
                                <img src="http://canvashtml-cdn.semicolonweb.com/images/team/4.jpg" alt="Nix Maxwell">
                              </div>
                              <div class="team-desc">
                                <div class="team-title"><h4>Nix Maxwell</h4><span>Support</span></div>
                                <a href="#" class="social-icon inline-block si-small si-light si-rounded si-facebook">
                                  <i class="icon-facebook"></i>
                                  <i class="icon-facebook"></i>
                                </a>
                                <a href="#" class="social-icon inline-block si-small si-light si-rounded si-twitter">
                                  <i class="icon-twitter"></i>
                                  <i class="icon-twitter"></i>
                                </a>
                                <a href="#" class="social-icon inline-block si-small si-light si-rounded si-gplus">
                                  <i class="icon-gplus"></i>
                                  <i class="icon-gplus"></i>
                                </a>
                              </div>
                            </div>

                          </div>
                        </div>

                      </div>
                      <div class="tab-content clearfix ui-tabs-panel ui-widget-content ui-corner-bottom" id="tab-reports" aria-labelledby="ui-id-4" role="tabpanel" aria-hidden="true" style="display: none;">


                      </div>

                    </div>

                  </div>
                  {% endcomment %}

                </div>

              </div>

            </div>
            <div class="col-sm-3 clearfix">

              <div class="list-group">
                <a href="{% url 'users:detail' %}" class="list-group-item clearfix">Profile <i class="icon-user pull-right"></i></a>
                <a href="#" class="list-group-item clearfix">Billing <i class="icon-credit-cards pull-right"></i></a>
                <a href="#" class="list-group-item clearfix">Settings <i class="icon-cog pull-right"></i></a>
                <a href="{% url 'account_logout' %}" class="list-group-item clearfix">Logout <i class="icon-line2-logout pull-right"></i></a>
              </div>

              <div class="fancy-title topmargin title-border">
                <h4>About Me</h4>
              </div>

              <p>{{user.bio|default:"We don't have a bio about you. Go to your settings to update your bio when you get a chance!"}}</p>


          </div>

        </div>

      </div>
    </section>
{% endblock content %}

political_sisterhood/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

political_sisterhood/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}