config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.views.generic.base import RedirectView
from political_sisterhood.pages.views import PageDetailView
from political_sisterhood.issue.views import IssueAutocomplete
from political_sisterhood.search.views import MySearchView
from .views import HomePage, Mailchimp, ContactUs

urlpatterns = [
    url(r'^$', HomePage.as_view(), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^news/$', TemplateView.as_view(template_name='pages/news.html'), name='news'),
    url(r'^contact-us/$', ContactUs.as_view(), name='contact'),
    url(r'^coming-soon/$', TemplateView.as_view(template_name='pages/soon.html'), name='coming-soon'),
    url(r'^issue-ac/', IssueAutocomplete.as_view(), name="issue-autocomplete"),
    # UTILITY VIEWS
    url(r'mailchimp-signup/$', Mailchimp, name='mailchimp'),
    url(r'^report_builder/', include('report_builder.urls')),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^profile/', include('political_sisterhood.users.urls', namespace='users')),
    url(r'^accounts/social/connections/$', RedirectView.as_view(pattern_name='users:redirect', permanent=True)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^candidates/', include('political_sisterhood.candidate.urls', namespace='candidate')),
    url(r'^races/', include('political_sisterhood.races.urls', namespace='races')),
    url(r'^jobs/', include('political_sisterhood.jobs.urls', namespace='jobs')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^admin/dynamic_raw_id/', include('dynamic_raw_id.urls')),
    url(r'^search/?$', MySearchView.as_view(), name='search'),

    # Your stuff: custom urls includes go here
    url(r'^(?P<slug>[\w.@+-]+)/$', PageDetailView.as_view()),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

political_sisterhood/candidate/urls.py
from django.conf.urls import include, url
from .views import CandidateView, StateListView, AllCandidates,\
                   UpdateCandidateInvite, CandidatePricing,\
                   CandidateIssueReport, CandidatePaywall,\
                   CreateCandidate
from django.views.generic import TemplateView
app_name = 'candidate'

urlpatterns = [
    url(r'^$',
        AllCandidates.as_view(),
        name='all'
        ),
    url(r'^pricing/$',
        TemplateView.as_view(template_name='pages/soon.html'),
        name='pricing'),
    url(r'^limit/$',
        CandidatePaywall.as_view(),
        name='paywall'
        ),
    url(r'^issue/$',
        CandidateIssueReport,
        name='issue'
        ),
    url(r'^update/(?P<hash>[\w.@+-]+)/$',
        UpdateCandidateInvite.as_view(),
        name='update'
        ),
    url(r'^create/$',
        CreateCandidate.as_view(),
        name='create'
        ),
    url(r'(?P<state>[\w.@+-]+)/(?P<slug>[\w.@+-]+)/$',
        CandidateView.as_view(),
        name='detail'
        ),
    url(r'(?P<state>[\w.@+-]+)/$',
        StateListView.as_view(),
        name='state'
        ),
]

political_sisterhood/jobs/urls.py
from django.conf.urls import include, url
from .views import JobsAll, JobsPost

app_name = 'jobs'

urlpatterns = [
    url(r'^$',
        JobsAll.as_view(),
        name='all'
    ),
    url(r'post/$',
        JobsPost.as_view(),
        name='post'
    ),
]

political_sisterhood/races/urls.py
from django.conf.urls import url
from .views import RaceAdd

app_name = 'races'

urlpatterns = [
    url(r'^add/$',
        RaceAdd.as_view(),
        name='all'
    ),

]

political_sisterhood/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^settings/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

political_sisterhood/search/models.py
# empty

political_sisterhood/candidate/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.views.generic import DetailView, CreateView,\
                                 TemplateView, UpdateView,\
                                 ListView, RedirectView
from django.core.mail import send_mail
from templated_email import send_templated_mail
from django.contrib import messages
from .models import Candidate, CandidateInvite, College, CandidateUpdate
from political_sisterhood.issue.models import CandidateIssue
from haystack.generic_views import SearchView as BaseFacetedSearchView
from political_sisterhood.races.models import State, Race
import logging
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .forms import CandidateForm
from political_sisterhood.search.forms import SearchForm
from haystack.query import SearchQuerySet, EmptySearchQuerySet, SQ
from haystack.inputs import AutoQuery
import urllib.parse as urlparse
logger = logging.getLogger(__name__)
# Create your views here.


def sendingEmail(candidate, new_data):
    candidate = Candidate.objects.get(id=candidate)
    from django.core import serializers
    try:
        send_templated_mail(
            template_name='updated',
            from_email="Political Sisterhood <info@politicalsisterhood.org>",
            recipient_list=['chris@politicalsisterhood.com',
                            'susan@politicalsisterhood.com'],
            context={
                'name': candidate.full_name,
                'url': candidate.get_absolute_url(),
                'candidate': candidate,
                'instance': new_data
            }
        )
    except Exception as e:
        logger.error(e)


class AllCandidates(BaseFacetedSearchView):
    template_name = "candidate/all.html"
    facet_fields= ['party']
    form_class = SearchForm
    paginate_by = 12
    paginate_orphans = 2

    # All CHANGES NEED TO BE DONE IN SEARCH/VIEWS AND CANDIDATE/VIEWS
    def get_queryset(self):
        queryset = SearchQuerySet().filter(active=True).order_by('first_name')
        # further filter queryset based on some set of criteria
        party = self.request.GET.getlist('party', '')
        party_or = ""
        college = self.request.GET.getlist('college', '')
        college_or = ""
        state = self.request.GET.getlist('state', '')
        state_or = ""
        issues = self.request.GET.getlist('issues', '')
        issues_or = ""
        race = self.request.GET.getlist('race', '')
        race_or = ""
        race_type = self.request.GET.getlist('race_type', '')
        race_type_or = ""
        women = self.request.GET.get('women', '')
        q = self.request.GET.get('q', '')
        page = self.request.GET.get('page', '')
        search = ''.join(party) + q + page
        if search == "":
            search = "null"
        if party:
            for facet in party:
                party_or += 'party: "%s"' % (facet)
            queryset = queryset.narrow(party_or)
        if college:
            for facet in college:
                college_or += 'college: "%s"' % (facet)
            queryset = queryset.narrow(college_or)
        if state:
            for facet in state:
                state_or += 'state: "%s"' % (facet)
            queryset = queryset.narrow(state_or)
        if issues:
            for facet in issues:
                issues_or += 'issues: "%s"' % (facet)
            queryset = queryset.narrow(issues_or)
        if race:
            for facet in race:
                race_or += 'race: "%s"' % (facet)
            queryset = queryset.narrow(race_or)
        if race_type:
            for facet in race_type:
                race_type_or += 'race_type: "%s"' % (facet)
            queryset = queryset.narrow(race_type_or)
        if q:
            queryset = queryset.filter(SQ(text=AutoQuery(q))|SQ(title=AutoQuery(q)))
        if women:
            queryset = queryset.filter(women=True)
        return queryset

    def form_valid(self, form):
        context = self.get_context_data(**{
            self.form_name: form,
            'object_list': self.get_queryset()
        })
        return self.render_to_response(context)

    def form_invalid(self, form):
        context = self.get_context_data(**{
            self.form_name: form,
            'object_list': self.get_queryset()
        })
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q','')
        context['party'] = self.request.GET.getlist('party', '')
        context['college'] = self.request.GET.getlist('college', '')
        context['state'] = self.request.GET.getlist('state', '')
        context['issues'] = self.request.GET.getlist('issues', '')
        women = self.request.GET.get('women', '')
        if women == True or women == 'on':
            context['women'] = True
        context['race_type'] = self.request.GET.getlist('race_type', '')
        return context


class CandidateView(DetailView):
    model = Candidate
    template_name = "candidate/detail.html"

    def dispatch(self, *args, **kwargs):
        user = self.request.user.is_authenticated
        if 'visited' in self.request.session:
            visits = self.request.session['visited']
        else:
            visits = None
        if not user:
            if visits and len(visits) > 3:
                return redirect(reverse('candidate:paywall'))
            visited = []
            candidate = self.get_object().id
            if visits:
                visited.extend(visits)
                if not candidate in visits:
                    visited.append(candidate)
            else:
                visited.append(candidate)
            self.request.session['visited'] = visited
        return super().dispatch(*args, **kwargs)

    def get_object(self):
        slug = self.kwargs['slug']
        candidate = Candidate.objects.get(slug=slug)
        return candidate

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['approved'] = False
        if self.request.GET.get('approved') == 'pending':
            context['approved'] = True
        elif self.get_object().approved:
            context['approved'] = True
        return context


class StateListView(ListView):
    model = Candidate
    template_name = "state/list.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        state =State.objects.get(state=self.kwargs['state'].upper())
        data['object'] = state
        return data

    def get_queryset(self):
        state = Candidate.objects.filter(state=self.kwargs['state'])
        return state


class UpdateCandidateInvite(UpdateView):
    # specify a custom ModelForm
    form_class = CandidateForm
    template_name = "candidate/update.html"

    def get_object(self, queryset=None):
        # get the existing object or created a new one
        candidate = get_object_or_404(CandidateInvite, md5_email=self.kwargs['hash'])
        if candidate.candidate:
            obj = Candidate.objects.get(id=candidate.candidate.id)
            CandidateInvite.objects.filter(md5_email=self.kwargs['hash']).update(candidate=obj)
        else:
            obj = None
        return obj

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['contact'] = CandidateInvite.objects.get(md5_email=self.kwargs['hash'])
        return data

    def form_valid(self, form):
        instance = form.save(commit=False)
        try:
            sendingEmail(instance.id, instance)
        except Exception as e:
            logger.error(e)
        instance.save()
        try:
            CandidateInvite.objects.filter(md5_email=self.kwargs['hash']).update(used=True)
            issue1, create = CandidateIssue.objects.get_or_create(candidate=instance,
                                                                  issue=form.cleaned_data.get('issue1'),
                                                                  desc=form.cleaned_data.get('issue1_detail'))
            issue2, created = CandidateIssue.objects.get_or_create(candidate=instance,
                                                                   issue=form.cleaned_data.get('issue2'),
                                                                   desc=form.cleaned_data.get('issue2_detail'))
            issue3, created = CandidateIssue.objects.get_or_create(candidate=instance,
                                                                   issue=form.cleaned_data.get('issue3'),
                                                                   desc=form.cleaned_data.get('issue3_detail'))
            college, create = College.objects.get_or_create(name=form.cleaned_data['college_free'])
            Candidate.objects.filter(id=instance.id).update(issue1=issue1.issue_num,
                                                            issue2=issue2.issue_num,
                                                            issue3=issue3.issue_num,
                                                            race_name=form.cleaned_data.get('race_name'),
                                                            college=college, approval="Pending")
            try:
                CandidateUpdate.objects.create(email=form.cleaned_data.get('update_email'),
                                               first_name=form.cleaned_data.get('update_first_name'),
                                               last_name=form.cleaned_data.get('update_last_name'),
                                               note=form.cleaned_data.get('update_note', ''),
                                               candidate=instance)
            except Exception as e:
                logger.error(e)
        except Exception as e:

political_sisterhood/issue/views.py
from dal import autocomplete
from django.utils.translation import ugettext as _
from django import http
from .models import Issue
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator


import logging

logger = logging.getLogger(__name__)

@method_decorator(csrf_exempt, name='dispatch')
class IssueAutocomplete(autocomplete.Select2QuerySetView):
    create_field = "name"

    def post(self, request):
        text = request.POST.get('text', None)

        if text is None:
            return http.HttpResponseBadRequest()

        parent = Issue.objects.get(name="Other")
        try:
            result, create = Issue.objects.get_or_create(name=text, parent=parent)
        except Exception as e:
            logger.error(e)

        return http.JsonResponse({
            'id': result.pk,
            'text': self.get_result_label(result),
        })

    def get_queryset(self):
        qs = Issue.objects.filter(parent__isnull=True)
        if self.q:
            qs = qs.filter(name__istartswith=self.q)
        return qs

    def get_create_option(self, context, q):
        """Form the correct create_option to append to results."""
        create_option = []
        display_create_option = False
        if self.create_field and q:
            display_create_option = True
            # Don't offer to create a new option if a
            # case-insensitive) identical one already exists
            existing_options = (self.get_result_label(result).lower()
                                for result in context['object_list'])
            if q.lower() in existing_options:
                display_create_option = False
        if display_create_option:
            create_option = [{
                'id': q,
                'text': _('Create "%(new_value)s"') % {'new_value': q},
                'create_id': True,
            }]
        return create_option

political_sisterhood/jobs/views.py
from django.shortcuts import render
from django.views.generic import DetailView, CreateView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class JobsAll(TemplateView):
    template_name = "jobs/all.html"

class JobsPost(LoginRequiredMixin, TemplateView):
    template_name = "jobs/post.html"

political_sisterhood/pages/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from .models import Page
# Create your views here.

class PageDetailView(DetailView):
    model = Page
    template_name = 'pages/detail.html'
    slug_url_kwarg = 'slug'

political_sisterhood/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

political_sisterhood/templates/base.html
{% load static i18n compress%}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block seo_title %}Political Sisterhood{% endblock seo_title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}

    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700|Raleway:300,400,500,600,700|Crete+Round:400i" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">


    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/font-icons.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/animate.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/print.css' %}" type="text/css" />
    {% endblock %}
    {% block extra_css %}
    {% endblock %}

  </head>

<body class="stretched">

  <!-- Document Wrapper
  ============================================= -->
  <div id="wrapper" class="clearfix">

    <!-- Header
    ============================================= -->
    <header id="header" class="full-header" >

      <div id="header-wrap">

        <div class="container clearfix">

          <div id="primary-menu-trigger"><i class="icon-reorder"></i></div>

          <!-- Logo
          ============================================= -->
          <div id="logo">
            <a href="{% url 'home' %}" class="standard-logo" data-dark-logo="{% static 'images/logo.png' %}"><img src="{% static 'images/logo.png' %}" alt="Politcical Sisterhood Logo" style="padding-top: 10px"></a>
            <a href="{% url 'home' %}" class="retina-logo" data-dark-logo="{% static 'images/logo.png' %}"><img src="{% static 'images/logo.png' %}" alt="Politcical Sisterhood Logo" style="padding-top: 10px"></a>
          </div><!-- #logo end -->

          <!-- Primary Navigation ============================================= -->
          <nav id="primary-menu">
            <ul>
              <li><a href="{% url 'about' %}"><div>About</div></a></li>
              <li><a style="cursor: unset;pointer-events: none;"><div>Run</div></a>
                <ul>
                  <li><a href="{% url 'candidate:create' %}"><div>I am a new candidate</div></a></li>
                   {% comment %}<li><a href="#"><div>Help my campaign</div></a></li>{% endcomment %}
                  {% comment %}<li><a href="#"><div>Nominate</div></a></li>{% endcomment %}
                </ul>

              </li>

              <li><a href="{% url 'candidate:all' %}"><div>Candidate Reports</div></a></li>
              <li><a href="https://www.psusanews.com/"><div>Resources</div></a>
                <!--
                <ul>
                  <li><a href="{% url 'coming-soon' %}"><div>Consultants</div></a></li>
                  <li><a href="{% url 'coming-soon' %}"><div>Training Organization</div></a></li>
                </ul>
              -->
              </li>
              <li><a href="{% url 'jobs:all' %}"><div>Jobs</div></a></li>
              <li><a href="{% url 'contact' %}"><div>Contact Us</div></a></li>
            </ul>
            <!-- Top Search ============================================= -->
            <div id="top-search">
              <a href="#" id="top-search-trigger"><i class="icon-search3"></i><i class="icon-line-cross"></i></a>
              <form action="/search" method="get">
                <input type="text" name="q" class="form-control" value="" placeholder="Type &amp; Hit Enter..">
              </form>
            </div><!-- #top-search end -->
          </nav>
        </div>
      </div>
    </header>

    <section id="content">
          {% if messages %}
              {% for message in messages %}
                  <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>{{ message }}</div>
              {% endfor %}
          {% endif %}

          {% block content %}
          <div class="container clearfix">
          </div> <!-- /container -->
          {% endblock content %}
        {% block fullwidth %}
        {% endblock %}
            <div class="content-wrap notoppadding">
          <a href="{% url 'coming-soon' %}" class="button button-full center tright footer-stick">
          <div class="container clearfix">
            Political Sisterhood needs your help! <strong>Find Out How</strong> <i class="icon-caret-right" style="top:4px;"></i>
          </div>
        </a>
    </div>
    </section>

          <!-- Footer
    ============================================= -->
    <footer id="footer" class="dark">

      <div class="container">

              <!-- Footer Widgets
        ============================================= -->
        <div class="footer-widgets-wrap clearfix">

          <div class="col_two_third">

            <div class="widget clearfix">

              <img src="{% static 'images/logo.png' %}" alt="" class="alignleft" style="height: 85px; margin-top: 8px; padding-right: 18px; border-right: 1px solid #b4b4b4;">

              <p>Political Sisterhood is a data collection and analysis firm for women in politics providing single-access portal for information and resources in support of women candidates regardless of political affiliation.</p>

              <div class="line" style="margin: 30px 0;"></div>

              <div class="col_one_third">
                <div class="widget clearfix">
                    <div class="col center">
                      <div class="counter counter-small" style="color: #c39;"><span data-from="100" data-to="{{CANDIDATE}}" data-refresh-interval="50" data-speed="2000" data-comma="true"></span></div>
                      <h5 class="nobottommargin">Candidates Represented</h5>
                    </div>
                </div>
              </div>

              <div class="col_two_third col_last">
                <div class="widget clearfix">
                  <h5><strong>Subscribe</strong> to Our Newsletter to get Important News, Candidate Information &amp; New Ways to Get Involved:</h5>
                  <form action="{% url 'mailchimp' %}" role="form" method="post" class="nobottommargin">
                    {% csrf_token %}
                    <div class="input-group divcenter">
                      <input type="email" name="email" class="form-control required email" placeholder="Enter your Email" required>
                      <div class="input-group-append">
                        <button class="button button-3d button-large button-brand nomargin" type="submit">Subscribe</button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>

            </div>

          </div>

          <div class="col_one_third col_last">

              <div class="widget widget-twitter-feed clearfix">

                <h4 class="theme-color">Twitter Feed</h4>
                <ul class="iconlist twitter-feed" data-username="politicalsister" data-count="2">
                  <li></li>
                </ul>

                <a href="https://twitter.com/@politicalsister" class="button button-3d button-large button-brand nomargin white-font">Follow Us on Twitter</a>
              </div>
            <div class="copyrights-menu copyright-links clearfix topmargin-lg">
              <a href="{% url 'about' %}">About</a>/
              <a href="{% url 'candidate:all' %}">Candidate Reports</a>/
              <a href="{% url 'jobs:all' %}">Jobs</a>/
              <a href="{% url 'contact' %}">Contact Us</a>/
              <a href="/privacy">Privacy Policy</a>/
              <a href="/intellectual-property">Intellectual Property</a>/
              <a href="/terms-and-conditions">Terms & Conditions</a>
            </div>
          </div>

        </div><!-- .footer-widgets-wrap end -->

      </div>

            <!-- Copyrights
      ============================================= -->
      <div id="copyrights">

        <div class="container clearfix">

          <div class="col_half">
            Copyright &copy; {% now 'Y' %} All Rights Reserved by Political Sisterhood, LLC.
          </div>

          <div class="col_half col_last tright">
            <div class="fright clearfix">
              <a href="https://www.facebook.com/politicalsisterhood/" class="social-icon si-small si-borderless nobottommargin si-facebook">
                <i class="icon-facebook"></i>
                <i class="icon-facebook"></i>
              </a>

              <a href="https://twitter.com/@politicalsister" class="social-icon si-small si-borderless nobottommargin si-twitter">
                <i class="icon-twitter"></i>
                <i class="icon-twitter"></i>
              </a>
              <a href="https://www.linkedin.com/company/politicalsisterhood/" class="social-icon si-small si-borderless nobottommargin si-linkedin">
                <i class="icon-linkedin"></i>
                <i class="icon-linkedin"></i>
              </a>
              <a href="#" class="social-icon si-small si-borderless nobottommargin si-youtube">
                <i class="icon-youtube"></i>
                <i class="icon-youtube"></i>
              </a>
            </div>
          </div>

        </div>

      </div><!-- #copyrights end -->

    </footer><!-- #footer end -->
    <div id="print" style="display: none">
        <h1>Welcome to Political Sisterhood</h1>
        <p>If you want the full details of this candidate, you'll need to login and register</p>
        <p>Once you are registered you can see up to three candidates information, for free</p>
        <p><strong>To get the most out of Political Sisterhood</strong>, we suggest buying credits to see detailed candidate information. We have information about everything from:
          <ul>
            <li>individual candidate summaries</li>
            <li>campaign summaries</li>
            <li>social media connections</li>
            <li>education and background</li>
            <li>Candidates stance on the issues</li>
          </ul>
        <br><br>
        <p>If you have any questions, please feel free to contact us at info@politicalsisterhood.com</p>
    </div>
    <div id="gotoTop" class="icon-angle-up"></div>

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-121795316-1"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-121795316-1');
      </script>

      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/jquery.js' %}"></script>
      <script src="{% static 'js/project.js' %}"></script>
      <script src="{% static 'js/plugins.js' %}"></script>
      <!-- Footer Scripts
      ============================================= -->
      <script src="{% static 'js/functions.js' %}"></script>

    {% endblock javascript %}
    {% block extra_js %}
    {% endblock %}
  </body>
</html>